### ISSUE TITLE
Upstream docker-related improvements

### ISSUE THREAD

**Issue by thebendavis** [GaloisInc/LLVM-MCA-Daemon#1]
We've made some changes while adding the PATE integration that we should review and upstream if appropriate:

- [ ] `docker/Dockerfile`: explicitly set `--platform=linux/amd64`
- [ ] `docker/compose.yml`: don't mount home directory
- [ ] `docker/compose.yml`: don't set `privileged: true`
- [ ] `docker/up`: use consistent name for resulting container
- [ ] `docker/up`: prefer `docker compose` to `docker-compose`
- [ ] `Dockerfile`: expose appropriate server port

**Comment by jim-carciofini** [comment]
Email from Ben for the record

> Hi Jim - just FYI, I sent updated text (below) to Chinmay to update their MCAD README.md with the appropriate acknowledgement text for the STTR, which he merged into upstream in [this PR](https://github.com/securesystemslab/LLVM-MCA-Daemon/pull/14). I wanted to share the context in case you see this diff when you compare/merge with your jcc-pate-binja MCAD branch - we'll want to make sure this latest contract #/etc text makes it into whatever branch of MCAD we deliver when we package everything up for the end of phase.
>
>Thanks,
>Ben

**Comment by jim-carciofini** [comment]
PR created: https://github.com/securesystemslab/LLVM-MCA-Daemon/pull/15

**Comment by jim-carciofini** [comment]
PR was accepted: https://github.com/securesystemslab/LLVM-MCA-Daemon/commit/30fce9391bd86f571c3011a68079156771266498
Done.
